import {
  Column,
  DataType,
  Model,
  PrimaryKey,
  Table,
} from 'sequelize-typescript';

/**
 * Shop product search row (R3 copy of `catalog.product_*` events). `searchVector` is generated by the database and
 * never written. No foreign key to the catalog (IX.4).
 */
@Table({
  modelName: 'SearchShopProduct',
  tableName: 'SearchShopProduct',
  timestamps: false,
})
export default class SearchShopProduct extends Model<
  SearchShopProduct,
  Partial<SearchShopProduct>
> {
  @PrimaryKey
  @Column({ type: DataType.UUID })
  declare productId: string;

  @Column({ type: DataType.UUID, allowNull: false })
  declare shopId: string;

  @Column({ type: DataType.TEXT, allowNull: false })
  declare title: string;

  @Column({ type: DataType.TEXT, allowNull: true })
  declare brand: string | null;

  @Column({ type: DataType.TEXT, allowNull: false })
  declare status: 'ACTIVE' | 'ARCHIVED';

  @Column({ type: DataType.BIGINT, allowNull: false })
  declare priceMinor: string;

  @Column({ type: DataType.CHAR(3), allowNull: false })
  declare currency: string;

  @Column({ type: DataType.INTEGER, allowNull: false })
  declare quantity: number;

  @Column({ type: DataType.BOOLEAN, allowNull: false })
  declare isSandbox: boolean;

  @Column({ type: DataType.BIGINT, allowNull: false })
  declare productVersion: string;

  @Column({ type: DataType.DATE, allowNull: true })
  declare deletedAt: Date | null;

  @Column({ type: DataType.DATE, allowNull: false })
  declare updatedAt: Date;
}
