/**
 * pnpm slo:generate - docs/slo/*.yaml → infra/observability/prometheus/rules/slo.generated.yml
 *                                     + scripts/load-tests/slo-thresholds.json
 * CI runs it and fails on a diff (generated files are committed, never edited by hand).
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseAllDocuments, stringify } from 'yaml';
import { k6Thresholds, sloRuleGroup, SloDefinition } from '@app/common/telemetry/slo-rules';

const root = resolve(__dirname, '../../../..');
const sloDir = join(root, 'docs/slo');

const slos: SloDefinition[] = readdirSync(sloDir)
  .filter((f) => f.endsWith('.yaml'))
  .sort()
  .flatMap((f) => parseAllDocuments(readFileSync(join(sloDir, f), 'utf8')).map((d) => d.toJSON() as SloDefinition));

const names = new Set<string>();
for (const s of slos) {
  if (names.has(s.name)) throw new Error(`duplicate SLO name ${s.name}`);
  names.add(s.name);
}

const header = '# GENERATED by `pnpm slo:generate` from docs/slo/*.yaml - do not edit.\n';
writeFileSync(join(root, 'infra/observability/prometheus/rules/slo.generated.yml'), header + stringify({ groups: slos.map(sloRuleGroup) }, { lineWidth: 0, aliasDuplicateObjects: false }));
writeFileSync(join(root, 'packages/backend/scripts/load-tests/slo-thresholds.json'), JSON.stringify(k6Thresholds(slos), null, 2) + '\n');
console.log(`generated rules for ${slos.length} SLOs`);
