import { HttpStatus } from '@nestjs/common';

// RFC 7807 Standard Error Response Interface (Public facing)
export interface AppErrorJSONPublic {
  /**
   * A URI reference that identifies the problem type.
   * Gives clients and APMs (Sentry/Datadog) a stable identifier for grouping/categorization.
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type.
   * Should NOT change between occurrences of the same error type (e.g., "Bad Request").
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server for this occurrence.
   */
  status: number;

  /**
   * A human-readable explanation specific to THIS occurrence of the problem.
   * Provides actionable details about why the operation failed.
   */
  detail: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * Standardized location for distributed tracing IDs (e.g. OpenTelemetry Trace ID).
   */
  instance?: string;
}

// Internal extended payload containing debugging and workflow controls
export interface AppErrorJSON extends AppErrorJSONPublic {
  /**
   * Custom structured contextual metadata relevant to the error occurrence.
   */
  data?: Record<string, any>;

  /**
   * Serialized tree of underlying root-cause errors.
   */
  causes?: any[];

  /**
   * The name of the error.
   */
  area: ErrorArea;
}

export enum ErrorArea {
  DOMAIN = 'DOMAIN',
  FATAL = 'FATAL',
  TRANSIENT = 'TRANSIENT',
}

// Dev-facing params perfectly align with the resulting JSON by extending AppErrorJSON
export interface AppErrorParams extends Omit<AppErrorJSON, 'type'> {
  detail: string;
  /**
   * Stable snake_case machine code (S54 FR-001). Required on the platform Fatal_/Transient_ classes; for legacy
   * domain subclasses that do not pass one it is derived from the class name.
   */
  code?: string;
  /** Extra non-reserved members merged into the problem document. */
  extensions?: Record<string, unknown>;
  /** Seconds for the `Retry-After` header. */
  retryAfterSeconds?: number;
  /** The idempotency facility stores this response as final. */
  idempotencyFinal?: boolean;
  /** Extra response headers (`WWW-Authenticate`, `Allow`, ...). */
  headers?: Record<string, string>;
}

const toSnakeCode = (name: string): string =>
  name
    .replace(/^(Domain|Fatal|Transient)_/, '')
    .replace(/Error$/, '')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toLowerCase() || 'internal_error';

/** Base URL of the `type` member; overridable with PROBLEM_TYPE_BASE_URL (config key `problem_type_base_url`). */
export const problemTypeBaseUrl = (): string =>
  process.env.PROBLEM_TYPE_BASE_URL ?? 'https://errors.marketplace.invalid';

export class AppError extends Error {
  public type: string;
  public code: string;
  public extensions?: Record<string, unknown>;
  public retryAfterSeconds?: number;
  public idempotencyFinal?: boolean;
  public headers?: Record<string, string>;
  public instance?: string;
  public status: HttpStatus;
  public title: string;
  // Note: 'detail' lives in the native `this.message` property set by super(params.detail)

  public data?: Record<string, any>;
  public causes?: Error[];
  public area: ErrorArea;

  constructor(params: AppErrorParams) {
    let nativeCause: Error | undefined = undefined;

    if (params.causes?.length) {
      nativeCause =
        params.causes.length === 1
          ? params.causes[0]
          : new AggregateError(params.causes, 'Multiple underlying causes');
    }

    // Pass the RFC 'detail' to the native JS Error 'message' (sets this.message = params.detail)
    super(params.detail, { cause: nativeCause });

    // Set the name to the exact class name (e.g., "BadRequestError") cause JS doesn't do it automatically. It helps Sentry and other tools to group it by standard 'name' field
    this.name = this.constructor.name;

    // Snip the constructor out of the stack trace so it points to the real bug
    Error.captureStackTrace(this, this.constructor);

    this.code = params.code ?? toSnakeCode(this.name);
    this.type = `${problemTypeBaseUrl()}/${this.code}`;
    this.extensions = params.extensions;
    this.retryAfterSeconds = params.retryAfterSeconds;
    this.idempotencyFinal = params.idempotencyFinal;
    this.headers = params.headers;
    this.title = params.title ?? 'An unexpected error occurred.';
    this.status = params.status ?? HttpStatus.INTERNAL_SERVER_ERROR;
    this.instance = params.instance;

    this.data = params.data;
    this.causes = params.causes || [];
    this.area = params.area ?? ErrorArea.FATAL;
  }

  toJSONPublic(): AppErrorJSONPublic {
    return {
      type: this.type,
      title: this.title,
      status: this.status,
      detail: this.message, // Native this.message holds params.detail
      instance: this.instance,
    };
  }

  /**
   * Serializes the error to exactly match the AppErrorJSON interface.
   */
  toJSON(includeDebugData = false): AppErrorJSON {
    const payload: AppErrorJSON = {
      ...this.toJSONPublic(),
      area: this.area,
    };

    if (includeDebugData) {
      if (this.data) payload.data = this.data;
      if (this.causes?.length) {
        payload.causes = this.causes.map(AppError.parseChildError);
      }
    }

    return payload;
  }

  toHRString(depth = 0): string {
    const indent = '  '.repeat(depth);
    let output = `${indent}❌ [${this.name}] ${this.message}`;

    if (this.data) {
      output += `\n${indent}   Data: ${JSON.stringify(this.data)}`;
    }

    if (this.causes?.length) {
      output += `\n${indent}   Caused by:`;
      for (const err of this.causes) {
        if (err instanceof AppError) {
          output += `\n${err.toHRString(depth + 1)}`;
        } else {
          output += `\n${indent}     - [${err.name}] ${err.message}`;
        }
      }
    }
    return output;
  }

  private static parseChildError(error: unknown): any {
    if (error instanceof AppError) return error.toJSON(true);
    if (error instanceof Error) {
      return {
        type: error.name,
        detail: error.message,
        stack: error.stack?.split('\n').map((line) => line.trim()),
      };
    }
    return error;
  }
}

/**
 * @description
 *    - Preconfigured set of errors, with some minor configuration options
 *    - Should be used by developers to avoid cases when they misconfigure which error is domain vs fatal/transient,
 *      since domain errors must be handled as a proper business response, while fatal errors must be forwarded to the DLQ topic
 *      and investigated by the team. As well as transient errors that happened too many times.
 *    - This list must only contain common Fatal and Transient errors. All Domain errors must be defined in the appropriate modules
 *    - Also, Domain errors should never be thrown, they are not exceptions. They are proper business responses that must be recorded in the database and communicated to the client.
 */
export type ConfiguredErrorParams = Partial<
  Pick<
    AppErrorParams,
    | 'title'
    | 'detail'
    | 'instance'
    | 'causes'
    | 'extensions'
    | 'retryAfterSeconds'
    | 'idempotencyFinal'
    | 'headers'
  >
>;

export class Fatal_BadRequestError extends AppError {
  constructor(params?: ConfiguredErrorParams) {
    super({
      code: 'validation_failed',
      status: HttpStatus.BAD_REQUEST,
      detail: 'Bad Request',
      title: 'Bad Request',
      area: ErrorArea.FATAL,
      ...params,
    });
  }
}

export class Fatal_InternalServerError extends AppError {
  constructor(params?: ConfiguredErrorParams) {
    super({
      code: 'internal_error',
      status: HttpStatus.INTERNAL_SERVER_ERROR,
      detail: 'Internal Server Error',
      title: 'Internal Server Error',
      area: ErrorArea.FATAL,
      ...params,
    });
  }
}

export class Fatal_RetriesExhaustedError extends AppError {
  constructor(params?: ConfiguredErrorParams) {
    super({
      code: 'internal_error',
      status: HttpStatus.INTERNAL_SERVER_ERROR,
      detail: 'Internal Server Error',
      title: 'Internal Server Error',
      area: ErrorArea.FATAL,
      ...params,
    });
  }
}

export class Fatal_NotFoundError extends AppError {
  constructor(params?: ConfiguredErrorParams) {
    super({
      code: 'not_found',
      status: HttpStatus.NOT_FOUND,
      detail: 'Not Found',
      title: 'Not Found',
      area: ErrorArea.DOMAIN,
      ...params,
    });
  }
}

/**
 * @description
 *    - Reserved for cases when a domain error is thrown to the outbox, which happens if a developer didn't process the business
 *      error gracefull as he was supposed to.
 */
export class Fatal_DomainErrorIsThrown extends AppError {
  constructor(params?: ConfiguredErrorParams) {
    super({
      code: 'internal_error',
      status: HttpStatus.INTERNAL_SERVER_ERROR,
      detail:
        'Domain errors should NEVER reach outbox. They must be hanlded gracefully in the appropriate module',
      title: 'Domain error is thrown to the outbox',
      area: ErrorArea.FATAL,
      ...params,
    });
  }
}

/**
 * @description
 *    - Reserved for cases if developer wants to explicitly mark an error as transient, for example
 *      a database connection error or a network error.
 */
export class Transient_InternalServerError extends AppError {
  constructor(params?: ConfiguredErrorParams) {
    super({
      code: 'internal_error',
      status: HttpStatus.INTERNAL_SERVER_ERROR,
      detail: 'Transient Error',
      title: 'Transient Error',
      area: ErrorArea.TRANSIENT,
      ...params,
    });
  }
}

/**
 * @description
 *    - Legacy `(detail, params)` constructor signature, kept for modules that
 *      pre-date the Fatal_/Domain_/Transient_ naming (stripe, aws-api,
 *      error-utils). New code should use the prefixed classes above.
 */
export class InternalServerError extends Fatal_InternalServerError {
  constructor(detail?: string, params?: ConfiguredErrorParams) {
    super({ ...params, detail: detail ?? 'Internal Server Error' });
  }
}

export class BadRequestError extends Fatal_BadRequestError {
  constructor(detail?: string, params?: ConfiguredErrorParams) {
    super({ ...params, detail: detail ?? 'Bad Request' });
  }
}

export class NotFoundError extends Fatal_NotFoundError {
  constructor(detail?: string, params?: ConfiguredErrorParams) {
    super({ ...params, detail: detail ?? 'Not Found' });
  }
}
