#!/usr/bin/env bash
# Writes packages/backend/.env for the DEV stack (docker-compose.yaml; ports 5300 postgres, 6300 redis, 9092 kafka, 9200 elasticsearch,
# 8123 clickhouse, 9100 minio, 9324 elasticmq, 8100 dynamodb (scylla alternator), 9042 scylla).
# The templates in packages/backend/env describe the TEST stack (ports 5400, 6400, 9192, ...), so they are merged
# (test.env.example, then showcase.env.example) and the dev ports are put on top. Never overwrites an existing .env unless FORCE=1.
set -euo pipefail
ROOT="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
OUT="$ROOT/packages/backend/.env"
if [[ -f "$OUT" && -z "${FORCE:-}" ]]; then echo "exists, left alone: $OUT (FORCE=1 to rewrite)"; exit 0; fi
python3 - "$ROOT/packages/backend/env/test.env.example" "$ROOT/packages/backend/env/showcase.env.example" "$OUT" <<'PY'
import sys
def read(p):
    d = {}
    for line in open(p):
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            k, v = line.split('=', 1)
            d[k] = v
    return d
cfg = read(sys.argv[1]); cfg.update(read(sys.argv[2]))
cfg.update({
    'NODE_ENV': 'local', 'PORT': '8000',
    'DB_HOST': 'localhost', 'DB_PORT': '5300', 'DB_USERNAME': 'postgres', 'DB_PASSWORD': 'postgres', 'DB_NAME': 'marketplace',
    'KAFKA_BROKER': 'localhost:9092',
    'REDIS_URL': 'redis://localhost:6300/0',
    'ELASTICSEARCH_NODE': 'http://localhost:9200',
    'CLICKHOUSE_URL': 'http://localhost:8123', 'CLICKHOUSE_DATABASE': 'marketplace',
    'S3_ENDPOINT': 'http://localhost:9100',
    'SQS_ENDPOINT': 'http://localhost:9324', 'SQS_QUEUE_URL_PREFIX': 'http://localhost:9324/000000000000/',
    'DYNAMO_ENDPOINT': 'http://localhost:8100', 'DYNAMO_TABLE_PREFIX': 'local_',
    'CASSANDRA_CONTACT_POINTS': 'localhost:9042',
})
with open(sys.argv[3], 'w') as f:
    f.write('# generated by scripts/infra/make-dev-env.sh: the dev stack (docker-compose.yaml); not committed\n')
    for k in sorted(cfg):
        f.write('%s=%s\n' % (k, cfg[k]))
print('wrote', sys.argv[3], '(%d keys)' % len(cfg))
PY
