import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, posix as pp } from 'node:path';
import type { DocsConfig } from './config.ts';
import type { FlowInfo, Graph, Unit } from './graph.ts';
import { buildConceptModel, conceptUses, resolveRefs, topOwners, type Concept, type ConceptModel } from './concepts.ts';
import { fileId, moduleId, SYSTEM_ID, unitId, type Outputs } from './nodes.ts';
import { Prose } from './prose.ts';
import { noteLink, theoryByConcept, theoryRefs, type TheoryRef } from './theory.ts';
import { bySort, clip, mdCell, slugify, uniq } from './util.ts';

export const MARKER = '<!-- generated by scripts/docs - do not edit by hand; regenerate with `pnpm docs:generate` -->';

type Meta = Record<string, string | number | boolean | string[]>;
const yamlValue = (v: Meta[string]): string => (Array.isArray(v) ? `[${v.map(yamlValue).join(', ')}]` : typeof v === 'string' ? JSON.stringify(v) : String(v));

interface Ctx { cfg: DocsConfig; graph: Graph; out: Outputs; stale: Set<string>; model: ConceptModel; usedBy: Map<string, string[]>; refs: TheoryRef[]; theory: Map<string, TheoryRef[]>; hasTheory: boolean }

const mid = (s: string) => s.replace(/[^A-Za-z0-9_]/g, '_');
const label = (s: string) => s.replace(/["[\]]/g, '');
const base = (p: string) => p.split('/').pop()!;

class Page {
  readonly path: string; // relative to outDir
  private readonly outDir: string;
  private readonly lines: string[] = [MARKER, ''];
  private front: Meta = {};
  private readonly prose: Prose;
  constructor(outDir: string, path: string, prose: Prose) {
    this.outDir = outDir;
    this.path = path;
    this.prose = prose;
  }
  /** Link to a section of a hand-written note (repo-relative path), from this page. */
  note(note: string, heading: string | null, text: string): string {
    return noteLink(pp.dirname(pp.join(this.outDir, this.path)), note, heading, text);
  }
  /** Model-written prose: identifiers in code spans, known symbols and concept titles linked. */
  t(text: string): string {
    return this.prose.fmt(text, this);
  }
  /** Frontmatter for this page. Keep it deterministic: pages are compared byte-for-byte by `check`. */
  meta(m: Meta): this {
    this.front = m;
    return this;
  }
  add(...ls: string[]): this {
    this.lines.push(...ls);
    return this;
  }
  /** Link to a source file (repo-relative) from this page. */
  src(file: string, line?: number, text = base(file)): string {
    const href = pp.relative(pp.dirname(pp.join(this.outDir, this.path)), file);
    return `[${text}](${href}${line ? `#L${line}` : ''})`;
  }
  /** Link to another generated page. */
  page(to: string, text: string): string {
    return `[${text}](${pp.relative(pp.dirname(this.path), to)})`;
  }
  toString(): string {
    const keys = Object.keys(this.front);
    const fm = keys.length ? `---\n${keys.map((k) => `${k}: ${yamlValue(this.front[k])}`).join('\n')}\n---\n` : '';
    return `${fm}${this.lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
  }
}

/** The concept page(s) a source file belongs to, as ` (link, link)`; empty when it belongs to none. */
function ownerLinks({ model }: Ctx, p: Page, file: string): string {
  const owners = topOwners(model, file);
  return owners.length ? ` (${owners.slice(0, 3).map((c) => p.page(c.page, c.title)).join(', ')})` : '';
}
const fileCell = (ctx: Ctx, p: Page, file: string) => `${p.src(file)}${ownerLinks(ctx, p, file)}`;

const noteTitle = (note: string) => (note.split('/').pop() ?? note).replace(/\.md$/, '').replace(/^\d+-/, '').replace(/-/g, ' ');

const unitPage = (u: Unit) => `units/${u.group}/${slugify(u.label.split('/').slice(1).join('-'))}.md`;
const flowPage = (f: FlowInfo) => `flows/${f.slug}.md`;

const staleBanner = (page: Page, isStale: boolean, missing: boolean) => {
  if (missing) page.add('> ⏳ _The AI-written parts of this page have not been generated yet; only facts extracted from the code are shown._', '');
  else if (isStale) page.add('> ⚠️ _Out of date: the code changed since these summaries were written. Regenerate to refresh._', '');
};

export function renderAll(cfg: DocsConfig, graph: Graph, out: Outputs, stale: Set<string>): Map<string, string> {
  const model = buildConceptModel(graph, out, { maxUses: cfg.maxConceptUses, maxDepth: cfg.maxConceptDepth, maxPerUnit: cfg.maxConceptsPerUnit });
  const usedBy = new Map<string, string[]>();
  for (const c of model.concepts) for (const u of conceptUses(c, out.get(c.id))) usedBy.set(u.concept, [...(usedBy.get(u.concept) ?? []), c.id]);
  const refs = theoryRefs(out, model, graph.files);
  const hasTheory = [...out.keys()].some((k) => k.startsWith('theory:'));
  const ctx: Ctx = { cfg, graph, out, stale, model, usedBy, refs, theory: theoryByConcept(refs, model), hasTheory };
  const prose = new Prose(graph, model);
  const pages: Page[] = [];
  const mk = (path: string) => (pages.push(new Page(cfg.outDir, path, prose)), pages[pages.length - 1]);

  renderIndex(ctx, mk('README.md'));
  renderSystem(ctx, mk('system.md'));
  for (const u of graph.units) renderUnit(ctx, mk(unitPage(u)), u);
  for (const c of model.concepts) renderConcept(ctx, mk(c.page), c);
  renderFlowIndex(ctx, mk('flows/index.md'));
  for (const f of graph.flows) renderFlow(ctx, mk(flowPage(f)), f);
  renderEvents(ctx, mk('catalog/events.md'));
  renderJobs(ctx, mk('catalog/jobs.md'));
  if (hasTheory) renderCoverage(ctx, mk('theory-coverage.md'));
  return new Map(pages.map((p) => [p.path, p.toString()]));
}

function renderIndex(ctx: Ctx, p: Page) {
  const { graph, out, stale, model } = ctx;
  const ids = [...out.keys()];
  const staleN = ids.filter((i) => stale.has(i)).length;
  p.meta({ type: 'codebase-map', tags: ['generated', 'codebase-map'], aliases: ['Codebase map'] });
  p.add('# Codebase map', '', '> Generated from the code. Each summary is cached against a hash of what it describes, so it is rewritten only when that code (or a summary below it) changes.', '');
  p.add(
    `- ${p.page('system.md', 'System overview')}: what the system is, how it is layered, and where to start reading`,
    `- ${p.page('flows/index.md', 'Async flows')}: how events and background jobs chain across units`,
    `- ${p.page('catalog/events.md', 'Event catalog')} and ${p.page('catalog/jobs.md', 'job catalog')}`,
    ...(ctx.hasTheory ? [`- ${p.page('theory-coverage.md', 'Theory coverage')}: which interview-prep sections are implemented here, and what is missing on either side`] : []),
    '',
    '## Units',
    '',
  );
  for (const group of uniq(graph.units.map((u) => u.group))) {
    p.add(`### ${group}`, '', '| Unit | Purpose |', '|---|---|');
    for (const u of graph.units.filter((x) => x.group === group)) p.add(`| ${p.page(unitPage(u), u.name)} | ${mdCell(out.get(unitId(u))?.purpose ?? '_not generated yet_')} |`);
    p.add('');
  }
  p.add('## Freshness', '', `${graph.files.size} source files, ${graph.units.length} units, ${model.concepts.length} capability and building-block pages, ${graph.flows.length} flows. ${ids.length} summaries available${staleN ? `, **${staleN} out of date**` : ', all up to date'}.`);
}

function renderSystem({ cfg, graph, out, stale }: Ctx, p: Page) {
  const sys = out.get(SYSTEM_ID);
  p.meta({ type: 'system', tags: ['generated', 'codebase-map', 'system'], aliases: ['System overview'] });
  p.add('# System overview', '');
  staleBanner(p, stale.has(SYSTEM_ID), !sys);
  if (sys) {
    p.add(p.t(sys.summary), '', '## Architecture', '', ...sys.architecture.map((a: string) => `- ${p.t(a)}`), '');
    if (sys.readingOrder.length) {
      p.add('## Suggested reading order', '');
      const byLabel = new Map(graph.units.map((u) => [u.label, u]));
      sys.readingOrder.forEach((r: { unit: string; why: string }, i: number) => p.add(`${i + 1}. ${p.page(unitPage(byLabel.get(r.unit)!), r.unit)}${r.why ? `: ${p.t(r.why)}` : ''}`));
      p.add('');
    }
  }
  const uById = new Map(graph.units.map((u) => [u.id, u]));
  const apps = graph.units.filter((u) => u.group === 'app');
  if (apps.length) {
    p.add('## Deployables and what they host', '', '| App | Pulls in |', '|---|---|');
    for (const a of apps) {
      const hosted = graph.unitEdges.filter((e) => e.from === a.id).map((e) => uById.get(e.to)!).filter((u) => u.group !== 'common');
      p.add(`| ${p.page(unitPage(a), a.label)} | ${mdCell(hosted.map((u) => u.name).join(', ') || '-')} |`);
    }
    p.add('');
  }
  const domainEdges = bySort(graph.unitEdges.filter((e) => uById.get(e.from)!.group === 'domain' && uById.get(e.to)!.group === 'domain'), (e) => `${String(1e6 - e.count).padStart(7, '0')}${e.from}`).slice(0, cfg.diagram.maxUnitEdges);
  if (domainEdges.length) {
    p.add('## Domain dependencies', '', '_An arrow means "imports from"; the number is how many import statements. Strongest links only._', '', '```mermaid', 'flowchart LR');
    for (const e of domainEdges) p.add(`  ${mid(e.from)}["${label(uById.get(e.from)!.name)}"] -->|${e.count}| ${mid(e.to)}["${label(uById.get(e.to)!.name)}"]`);
    p.add('```', '');
  }
  if (graph.flows.length) {
    p.add('## Async flows', '');
    for (const f of graph.flows) p.add(`- ${p.page(flowPage(f), out.get(f.id)?.title ?? f.slug)}`);
  }
}

function renderUnit(ctx: Ctx, p: Page, u: Unit) {
  const { graph, out, stale, model } = ctx;
  const o = out.get(unitId(u));
  const uById = new Map(graph.units.map((x) => [x.id, x]));
  p.meta({ type: 'unit', tags: ['generated', 'codebase-map', `unit/${u.group}`], aliases: [u.label], group: u.group, unit: u.name, root: u.id, files: u.files.length });
  p.add(`# ${u.label}`, '');
  staleBanner(p, stale.has(unitId(u)), !o);
  if (o) p.add(`> ${p.t(o.purpose)}`, '');
  const routes = u.files.flatMap((f) => (graph.files.get(f)?.routes ?? []).map((r) => ({ ...r, file: f })));
  p.add(`\`${u.id}\` · ${u.files.length} files · ${routes.length} handlers`, '');
  if (o) {
    if (o.summary) p.add('## How it works', '', p.t(o.summary), '');
  }
  const mine = model.byUnit.get(u.id) ?? [];
  const top = mine.filter((c) => c.depth === 0);
  if (top.length) p.add('## Topics', '', ...top.map((c) => `- ${p.page(c.page, c.title)}${c.gist ? `: ${p.t(c.gist)}` : ''}`), '');
  const covered = new Set(mine.flatMap((c) => c.files));
  const loose = u.files.filter((f) => !covered.has(f) && !graph.files.get(f)?.isTrivial);
  if (mine.length && loose.length) p.add('## Files outside any topic', '', ...loose.map((f) => `- ${p.src(f, undefined, f.slice(u.id.length + 1))}`), '');
  if (o) {
    if (o.concepts.length) p.add('## Key concepts', '', '| Term | Meaning |', '|---|---|', ...o.concepts.map((c: any) => `| ${mdCell(p.t(c.term))} | ${mdCell(p.t(c.meaning))} |`), '');
    if (o.gotchas.length) p.add('## Gotchas', '', ...o.gotchas.map((g: string) => `- ${p.t(g)}`), '');
    if (o.startHere.length) p.add('## Start here', '', ...o.startHere.map((s: any) => `- ${p.src(s.path, undefined, s.path.slice(u.id.length + 1))}${s.why ? `: ${p.t(s.why)}` : ''}`), '');
  }

  p.add('## Modules', '');
  for (const m of u.modules) {
    const mo = out.get(moduleId(m));
    p.add(`### ${m.name}`, '');
    if (mo?.summary) p.add(p.t(mo.summary), '');
    p.add('| File | What it does |', '|---|---|');
    for (const f of m.files) {
      const fo = out.get(fileId(f));
      const syms = fo?.symbols?.filter((s: any) => s.summary).slice(0, 4) ?? [];
      p.add(`| ${p.src(f, undefined, f.slice(u.id.length + 1))} | ${mdCell(p.t(clip(`${fo?.purpose ?? '_not generated yet_'}${syms.length ? ` — ${syms.map((s: any) => `\`${s.name}\`: ${s.summary}`).join('; ')}` : ''}`, 600)))} |`);
    }
    p.add('');
  }

  p.add('## Interfaces', '');
  if (routes.length) {
    p.add(`<details><summary>HTTP / GraphQL / message handlers (${routes.length})</summary>`, '', '| Method | Path | Handler |', '|---|---|---|');
    for (const r of routes) p.add(`| ${r.method} | \`${r.path}\` | ${p.src(r.file, r.line, r.handler)} |`);
    p.add('', '</details>', '');
  }
  const inUnit = new Set(u.files);
  const pubs = graph.events.filter((e) => e.producers.some((f) => inUnit.has(f)));
  const subs = graph.events.filter((e) => e.consumers.some((f) => inUnit.has(f)));
  if (pubs.length) p.add('**Publishes events:** ' + pubs.map((e) => `\`${e.name}\``).join(', '), '');
  if (subs.length) p.add('**Consumes events:** ' + subs.map((e) => `\`${e.name}\``).join(', '), '');
  const handled = graph.jobs.filter((j) => j.handlers.some((h) => inUnit.has(h.file)));
  if (handled.length) p.add('**Background jobs handled:** ' + handled.map((j) => `\`${j.name}\`${j.schedules[0] ? ` (\`${j.schedules[0].cron}\`)` : ''}`).join(', '), '');
  if (pubs.length || subs.length || handled.length) p.add(`See ${p.page('catalog/events.md', 'event catalog')} and ${p.page('catalog/jobs.md', 'job catalog')}.`, '');

  const dep = graph.unitEdges.filter((e) => e.from === u.id);
  const used = graph.unitEdges.filter((e) => e.to === u.id);
  p.add('## Dependencies', '');
  const fmt = (es: typeof dep, pick: 'to' | 'from') => es.map((e) => `${p.page(unitPage(uById.get(e[pick])!), uById.get(e[pick])!.label)} (${e.count})`).join(', ') || '_none_';
  p.add(`**Imports from:** ${fmt(dep, 'to')}`, '', `**Imported by:** ${fmt(used, 'from')}`, '');
  const myFlows = graph.flows.filter((f) => f.files.some((x) => inUnit.has(x)));
  if (myFlows.length) p.add('## Flows it takes part in', '', ...myFlows.map((f) => `- ${p.page(flowPage(f), out.get(f.id)?.title ?? f.slug)}`), '');
}

function renderConcept(ctx: Ctx, p: Page, c: Concept) {
  const { graph, out, stale, model, usedBy } = ctx;
  const o = out.get(c.id);
  const link = (t: Concept, text: string) => p.page(t.page, text);
  p.meta({ type: 'concept', tags: ['generated', 'codebase-map', 'concept', `unit/${c.unit.group}`], aliases: [c.title], unit: c.unit.label, depth: c.depth, files: c.files.length });
  p.add(`# ${c.title}`, '');
  staleBanner(p, stale.has(c.id), !o);
  const partOf = c.parents.length ? c.parents.map((id) => link(model.byId.get(id)!, model.byId.get(id)!.title)).join(', ') : p.page(unitPage(c.unit), c.unit.label);
  p.add(`> ${p.t(o?.summary ?? c.gist)}`, '', `_Part of ${partOf}_`, '');
  if (o) {
    p.add(p.t(resolveRefs(o.story, c, model, o.parts, link)), '');
    if (o.lives.length) p.add('**Look at:** ' + o.lives.map((l: any) => p.src(l.file, l.line, l.symbol ? `\`${l.symbol}\` in ${base(l.file)}` : base(l.file))).join(' · '), '');
    const pieces = o.parts.map((x: any) => {
      const target = x.reuse ? model.byId.get(x.reuse) : c.children.map((id) => model.byId.get(id)!).find((k) => k.slug === x.slug);
      return `- ${target ? link(target, x.title) : x.title}${x.what ? `: ${p.t(x.what)}` : ''}`;
    });
    if (pieces.length) p.add('## Pieces', '', ...pieces, '');
    if (o.data.length) p.add('## What it touches', '', '| Kind | Name | How |', '|---|---|---|', ...o.data.map((d: any) => `| ${d.kind} | ${mdCell(p.t(`\`${d.name}\``))} | ${mdCell(p.t(d.how))} |`), '');
  }
  const uses = conceptUses(c, o);
  if (uses.length) {
    p.add('## Also relies on', '');
    for (const u of uses) {
      const t = model.byId.get(u.concept)!;
      p.add(`- ${link(t, t.title)}${t.unit.id === c.unit.id ? '' : ` (${t.unit.label})`}${u.how ? `: ${p.t(u.how)}` : ''}`);
    }
    p.add('');
  }
  if (o?.gotchas?.length) p.add('## Watch out', '', ...o.gotchas.map((g: string) => `- ${p.t(g)}`), '');
  const users = (usedBy.get(c.id) ?? []).map((id) => model.byId.get(id)!);
  const mine = new Set(c.files);
  const flows = c.files.length ? graph.flows.filter((f) => f.files.some((x) => mine.has(x))) : [];
  if (users.length || flows.length) {
    p.add('## Used by', '');
    for (const x of users) p.add(`- ${link(x, x.title)} (${x.unit.label})`);
    for (const f of flows) p.add(`- flow: ${p.page(flowPage(f), out.get(f.id)?.title ?? f.slug)}`);
    p.add('');
  }
  const theoryHere = uniq((ctx.theory.get(c.id) ?? []).map((r) => `${r.note}\u0000${r.key}`)).map((k) => ctx.theory.get(c.id)!.find((r) => `${r.note}\u0000${r.key}` === k)!);
  if (theoryHere.length) p.add('## Theory', '', ...theoryHere.map((r) => `- ${p.note(r.note, r.heading, `${noteTitle(r.note)} › ${r.heading}`)}`), '');
  const libs = uniq(c.contextFiles.flatMap((f) => graph.externals.get(f) ?? [])).sort();
  if (c.files.length || libs.length) {
    p.add('<details><summary>Files and libraries</summary>', '');
    if (c.files.length) p.add('| File | What it does |', '|---|---|', ...c.files.map((f) => `| ${p.src(f, undefined, f.slice(c.unit.id.length + 1))} | ${mdCell(p.t(out.get(fileId(f))?.purpose ?? '_not generated yet_'))} |`), '');
    if (libs.length) p.add(`Libraries: ${libs.map((l) => `\`${l}\``).join(', ')}`, '');
    p.add('</details>', '');
  }
}

function renderCoverage(ctx: Ctx, p: Page) {
  const { out, model } = ctx;
  p.meta({ type: 'theory-coverage', tags: ['generated', 'codebase-map', 'theory'], aliases: ['Theory coverage'] });
  p.add('# Theory coverage', '', 'How the hand-written notes in the theory folder line up with this codebase. Links in the notes themselves sit in an **In this codebase** block under each section.', '');
  const notes = [...out].filter(([id]) => id.startsWith('theory:')).map(([, o]) => o).sort((a: any, b: any) => (a.note < b.note ? -1 : 1));
  p.add('## Notes', '', '| Note | Sections linked to code | Substantial sections with no counterpart |', '|---|---|---|');
  for (const o of notes as any[]) p.add(`| ${p.note(o.note, null, noteTitle(o.note))} | ${o.sections.length} | ${o.gaps.length} |`);
  p.add('');
  const gaps = (notes as any[]).filter((o) => o.gaps.length);
  if (gaps.length) {
    p.add('## Theory with no code counterpart', '', '_Candidates to build in this project, or to mark as out of scope._', '');
    for (const o of gaps) p.add(`- **${noteTitle(o.note)}**: ${o.gaps.map((g: any) => p.note(o.note, g.heading, g.heading)).join(' · ')}`);
    p.add('');
  }
  const linked = new Set(ctx.theory.keys());
  const orphans = model.concepts.filter((c) => c.depth === 0 && !linked.has(c.id));
  if (orphans.length) {
    p.add('## Code with no theory note', '', '_Top-level topics that no theory section links to: material for new notes._', '');
    for (const unit of uniq(orphans.map((c) => c.unit.label))) p.add(`- **${unit}**: ${orphans.filter((c) => c.unit.label === unit).map((c) => p.page(c.page, c.title)).join(' · ')}`);
    p.add('');
  }
}


function renderFlowIndex({ graph, out }: Ctx, p: Page) {
  p.meta({ type: 'flow-index', tags: ['generated', 'codebase-map', 'flow'], aliases: ['Async flows'] });
  p.add('# Async flows', '', 'Chains where one unit publishes a domain event or enqueues a job that another file consumes or handles. Found by static analysis of `defineEvent` / `@JobHandler` / `enqueue` usage.', '');
  p.add('| Flow | Units | Hops |', '|---|---|---|');
  for (const f of graph.flows) p.add(`| ${p.page(flowPage(f), out.get(f.id)?.title ?? f.slug)} | ${mdCell(f.units.join(', '))} | ${f.edges.length} |`);
}

function renderFlow(ctx: Ctx, p: Page, f: FlowInfo) {
  const { cfg, graph, out, stale, model } = ctx;
  const o = out.get(f.id);
  p.meta({ type: 'flow', tags: ['generated', 'codebase-map', 'flow'], aliases: [o?.title ?? f.slug], units: f.units, hops: f.edges.length });
  p.add(`# ${o?.title ?? f.slug}`, '');
  staleBanner(p, stale.has(f.id), !o);
  if (o) p.add(p.t(o.summary), '');
  p.add(`**Units:** ${f.units.join(', ')}`, '');
  const edges = f.edges.slice(0, cfg.maxFlowEdges);
  p.add('```mermaid', 'flowchart LR');
  const nodes = uniq(edges.flatMap((e) => [e.from, e.to]));
  const uLabel = (file: string) => graph.units.find((u) => u.id === graph.unitOfFile.get(file))?.name ?? '';
  for (const n of nodes) p.add(`  ${mid(n)}["${label(base(n))}<br/>${label(uLabel(n))}"]`);
  for (const e of edges) p.add(`  ${mid(e.from)} -->|"${e.via === 'job' ? 'job: ' : ''}${label(e.name)}"| ${mid(e.to)}`);
  p.add('```', '', '## Steps', '', '| # | Hop | Producer | Consumer | What happens |', '|---|---|---|---|---|');
  const narr = new Map<number, string>((o?.steps ?? []).map((s: any) => [s.ref, s.narrative]));
  edges.forEach((e, i) => p.add(`| ${i} | ${e.via} \`${e.name}\` | ${fileCell(ctx, p, e.from)} | ${fileCell(ctx, p, e.to)} | ${mdCell(p.t(narr.get(i) ?? ''))} |`));
  if (f.edges.length > edges.length) p.add('', `_${f.edges.length - edges.length} more hops not shown._`);
  p.add('');
  const involved = uniq(f.files.flatMap((x) => topOwners(model, x).slice(0, 1).map((c) => c.id))).map((id) => model.byId.get(id)!);
  if (involved.length) p.add('## Capabilities involved', '', ...involved.map((c) => `- ${p.page(c.page, c.title)} (${c.unit.label})`), '');
  if (o?.notes?.length) p.add('## Notes', '', ...o.notes.map((n: string) => `- ${p.t(n)}`), '');
  if (f.entrypoints.length) p.add('## Likely entry points', '', '_Request handlers whose files import (within two hops) code in this flow; a heuristic, not a trace._', '', ...f.entrypoints.map((e) => `- \`${e.method} ${e.path}\` in ${p.src(e.file, e.line)}`), '');
}

function renderEvents(ctx: Ctx, p: Page) {
  const { graph } = ctx;
  const list = (fs: string[]) => (fs.length ? fs.map((f) => fileCell(ctx, p, f)).join('<br/>') : '-');
  p.meta({ type: 'catalog', tags: ['generated', 'codebase-map', 'catalog'], aliases: ['Event catalog'] });
  p.add('# Domain event catalog', '', '| Event | Aggregate | Defined in | Published by | Consumed by |', '|---|---|---|---|---|');
  for (const e of graph.events) p.add(`| \`${e.name}\` | ${e.aggregate} | ${p.src(e.definedIn, e.line)} | ${list(e.producers)} | ${list(e.consumers)} |`);
}

function renderJobs(ctx: Ctx, p: Page) {
  const { graph } = ctx;
  p.meta({ type: 'catalog', tags: ['generated', 'codebase-map', 'catalog'], aliases: ['Job catalog'] });
  p.add('# Background job catalog', '', '| Job | Handler | Enqueued by | Schedule |', '|---|---|---|---|');
  for (const j of graph.jobs) {
    const handlers = j.handlers.length ? j.handlers.map((h) => `${p.src(h.file, h.line, `${base(h.file)}#${h.handler}`)}${ownerLinks(ctx, p, h.file)}`).join('<br/>') : '-';
    const enq = j.enqueuers.length ? j.enqueuers.map((f) => fileCell(ctx, p, f)).join('<br/>') : '-';
    p.add(`| \`${j.name}\` | ${handlers} | ${enq} | ${j.schedules.map((s) => `\`${s.cron}\``).join(', ') || '-'} |`);
  }
}

// ------------------------------------------------------------------ disk IO

function listGenerated(dir: string, rel = ''): string[] {
  const full = join(dir, rel);
  if (!existsSync(full)) return [];
  const out: string[] = [];
  for (const name of readdirSync(full)) {
    if (name.startsWith('.')) continue; // .cache etc.
    const r = rel ? `${rel}/${name}` : name;
    if (statSync(join(dir, r)).isDirectory()) out.push(...listGenerated(dir, r));
    else if (name.endsWith('.md')) out.push(r);
  }
  return out;
}

export interface WriteReport { written: string[]; removed: string[]; unchanged: number }

/** Compares (and optionally applies) rendered pages against disk. The output dir is owned by the generator: any other .md file in it is removed. */
export function syncOutputs(root: string, outDir: string, pages: Map<string, string>, apply: boolean): WriteReport {
  const dir = join(root, outDir);
  const rep: WriteReport = { written: [], removed: [], unchanged: 0 };
  for (const [path, content] of [...pages].sort()) {
    const file = join(dir, path);
    const existing = existsSync(file) ? readFileSync(file, 'utf8') : null;
    if (existing === content) rep.unchanged++;
    else {
      rep.written.push(path);
      if (apply) (mkdirSync(dirname(file), { recursive: true }), writeFileSync(file, content));
    }
  }
  for (const path of listGenerated(dir)) {
    if (pages.has(path)) continue;
    const file = join(dir, path);
    rep.removed.push(path);
    if (apply) rmSync(file);
  }
  return rep;
}
